package com.malka.androidappp.servicemodels

import org.joda.time.DateTime

data class CreateAdvMainModel(
    val Id: String? = null,
    val City: String? = null,
    val Country: String? = null,
    val name: String? = null,
    val slug: String? = null,
    val Template: String? = null,
    val Region: String? = null,
    val Urgentexpirydate: String? = null,
    val Title: String? = null,
    val Price: String? = null,
    val user: String? = null,
    val StartingPrice: String? = null,
    val ReservePrice: String? = null,
    val Duration: String? = null,
    val EndTime: String? = null,
    val FixLength: String? = null,
    val Timepicker: String? = null,
    val DateTime: String? = null,
    val createdBy: String? = null,
    val updatedOn: String? = null,
    val updatedBy: String? = null,
    val isActive: Boolean? = false,
    var Images: List<String>? = null,
    val referenceId: String? = null,
    val isWatching: Boolean? = false,
    val Isuserfavorite: Boolean? = false,
    val listingType: String? = null,
    val quantity: String? = null,
    val featureexpirydate: String? = null,
    val highlightexpirydate: String? = null,
    val phone: String? = null,
    val address: String? = null,
    val pickupOption: String? = null,
    val shippingOption: String? = null,
    val pack4: String? = null,
    val description: String? = null,
    val subtitle: String? = null,
    val producttitle: String? = null,
    val brand_new_item: String? = null,
    val enddate: String? = null,
    val createdOn: DateTime? = null,
    val platform: String? = null,
    val isbankpaid: String? = null,
    val iscashpaid: String? = null,
    val subcatone: String? = null,
    val subcattwo: String? = null,
    val subcatthree: String? = null,
    val subcatfour: String? = null,
    val subcatfive: String? = null,
    val subcatsix: String? = null,
    val subcatonekey: String? = null,
    val subcattwokey: String? = null,
    val subcatthreekey: String? = null,
    val subcatfourkey: String? = null,
    val subcatfivekey: String? = null,
    val subcatsixkey: String? = null,
    val category: String? = null,
    val Video: String? = null
)
