package com.malka.androidappp.botmnav_fragments.activities_main.business_signup

data class ModelBusinessRegistration(
    val alternateEmail: String? = null,
    val bUsername: String? = null,
    val BillingAddress: String? = null,
    val businessSubuser: String? = null,
    val BusinessName: String? = null,
    val bussinesPhoneNum: String? = null,
    val bussinessAddress: String? = null,
    val BussinessDescription: String? = null,
    val bussinessExpiryDate: String? = null,
    val bussinessTagline: String? = null,
    val bussinessTypeId: String? = null,
    val bussinessWebsite: String? = null,
    val country: String? = null,
    val createdBy: String? = null,
    val createdOn: String? = null,
    val email: String? = null,
    val fullName: String? = null,
    val googleMapPin: String? = null,
    val id: String? = null,
    val isActive: Boolean? = false,
    val isApproved: Boolean? = false,
    val lastname: String? = null,
    val password: String? = null,
    val phone: String? = null,
    val regNumber: String? = null,
    val updatedBy: String? = null,
    val updatedOn: String? = null,
    val username: String? = null,
    val filepond: List<String>? = null,
)