package com.malqaa.androidappp.newPhase.domain.models.productResp

import com.malqaa.androidappp.newPhase.domain.models.ImageSelectModel
import com.malqaa.androidappp.newPhase.domain.models.dynamicSpecification.DynamicSpecificationSentObject
import com.malqaa.androidappp.newPhase.domain.models.pakatResp.PakatDetails
import com.malqaa.androidappp.newPhase.domain.models.servicemodels.Category

data class Product(
    val businessAccountId: Int? = null,
    val providerId: String? = null,
    val acceptQuestion: Boolean,
    val isFixedPriceEnabled: Boolean,
    val isAuctionEnabled: Boolean,
    val isNegotiationEnabled: Boolean,
    val price: Float,
    var priceDisc: Float,
    var priceDiscount: Float,
    var paymentOptionId: Int,
    val isCashEnabled: Boolean,
    val auctionStartPrice: Float,
    val disccountEndDate: String? = null,
    val sendOfferForAuction: Boolean,
    val isAuctionClosingTimeFixed: Boolean,
    val auctionMinimumPrice: Float,
    val auctionNegotiateForWhom: String? = null,
    val auctionNegotiatePrice: Float,
    val auctionClosingTime: String? = null,
    val id: Int,
    var productPosition: Int,
    val isActive: Boolean,
    val isDelete: Boolean,
    val name: String? = null,
    val nameAr: String? = null,
    val nameEn: String? = null,
    val subTitle: String? = null,
    val subTitleAr: String? = null,
    val subTitleEn: String? = null,
    val description: String? = null,
    val descriptionAr: String? = null,
    val descriptionEn: String? = null,
    val qty: Int,
    val productImage: String? = null,
    val isAuctionPaied: Boolean,
    val status: Int,
    val countView: Int,
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val categoryId: Int,
    val categoryDto: Category? = null,
    val category: String? = null,
    val countryId: Int,
    val country: String? = null,
    val regionId: Int,
    val regionName: String? = null,
    val neighborhoodId: Int,
    val neighborhood: String? = null,
    val district: String? = null,
    val street: String? = null,
    val governmentCode: String? = null,
    val pakatId: Int,
    var isFavourite: Boolean,
    val pickUpDeliveryOption: String? = null,
    val productShippingOptions: List<PorductShippingOptionItem>? = null,
    val isFreeDelivery: Boolean,
    val isMerchant: Boolean,
    val isFeatured: Boolean,
    val negotiationOffersCount: Int,
    val purchasedQuantity: Int,
    val restQuantity: Int,
    val addedToFavoritsCount: Int,
    val viewsCount: Int,
    val lat: String? = null,
    val lon: String? = null,
    val listMedia: ArrayList<ImageSelectModel>? = null,
    val listProductSep: List<DynamicSpecificationSentObject>? = null,
    val productMazadNegotiate: ProductMazadNegotiateObject? = null,
    var highestBidPrice: Float,
    var bankAccountId: Int,
    var image: String? = null,
    var myBid: Float,
    var productPublishPrice: Float,
    var selectedPacket: PakatDetails? = null,
)
