package com.malka.androidappp.botmnav_fragments.create_ads

import com.google.gson.annotations.SerializedName

data class ModelDataCreateAutoMobile(

    val images: List<String>? = null,
    val id:String? = null,
    val platenumber:String? = null,
    val body:String? = null,
    val model:String? = null,
    val make:String? =null,
    val year:String? = null,
    val kilometers:String? = null,
    val fuel:String? = null,
    val squencenumber:String? = null,
    val cylinders:String? = null,
    val featureexpirydate:String? = null,
    val urgentexpirydate:String? = null,
    val highlightexpirydate:String? = null,
    val producttitle:String? = null,
    val Template:String? = null,
    val selectasmain:String? = null,
    val title:String? = null,
    val user:String? = null,
    val subtitle:String? = null,
    val quantity:String? = null,
    val phone:String? = null,
    val country:String? = null,
    val region:String? = null,
    val city:String? = null,
    val address:String? = null,
    val description:String? = null,
    @SerializedName("brand-new-item") var brand_new_item:Any? = 0,
    val price:String? = null,
    val cash_pm:String? = null,
    val sa_bank_pm:String? = null,
    val fixLength:String? = null,
    val timepicker:String? = null,
    @SerializedName("pickup-option") var pickup_option:String? = null,
    @SerializedName("shipping-option") var shipping_option:String? = null,
    @SerializedName("cost-amount") var cost_amount:String? = null,
    @SerializedName("cost-desc") var cost_desc:String? = null,
    val pack4:String? = null,
    val sellertype:String? = null,
    val noofpreviousowners:String? = null,
    val motorvehiclesperiodicinspection:String? = null,
    val transmission:String? = null,
    val isimported:Boolean? = false,
    val isnogotiable:Boolean? = false

)