package com.malka.androidappp.botmnav_fragments.my_product.edit_product

import java.util.*

data class ModelEditProduct(

    val id: String? = null,
    val userId: String? = null,
    val code: String? = null,
    val sKU: String? = null,
    val title: String? = null,
    val subTitle: String? = null,
    val brand: String? = null,
    val barcodeGTIN: String? = null,
    val images: List<String>? = null,
    val manufacturersCode: String? = null,
    val stock: String? = null,
    val listingDuration: String? = null,
    val specifyEndTime: String? = null,
    val description: String? = null,
    val unwantedChristmasgift: String? = null,
    val color: String? = null,
    val size: String? = null,
    val ddlbrand: String? = null,
    val BuyNow: String? = null,
    val startPrice: String? = null,
    val specifyReserve: String? = null,
    val fixedPriceOffer: String? = null,
    val offerDuration: String? = null,
    val OfferTo: String? = null,
    val Length: String? = null,
    val Width: String? = null,
    val Height: String? = null,
    val Weight: String? = null,
    val extrasListingOffers: String? = null,
    val activateAutoListing: String? = null,
    val BuyNowAuction: String? = null,
    val ShippingOptions: String? = null,
    val PickUp: String? = null,
    val onlyAllowBidsFromAuthenticatedMembers: Boolean? = false,
    val isfixedPriceOffer: Boolean? = false,
    val saudiBankDeposit: Boolean? = false,
    val ping: Boolean? = false,
    val cash: Boolean? = false,
    val iDontknowTheShippingCostsYet: Boolean? = false,
    val freeShippingWithinSaudia: Boolean? = false,
    val useBookACourierShippingCosts: Boolean? = false,
    val specifyShippingCosts: Boolean? = false,
    val useShippingTemplate: Boolean? = false,
    val UnlimitedStock: Boolean? = false,
    val Paypal: Boolean? = false,
    var ListingType: String? = null,
    val CreatedDate: Date? = null,
    val updatedon: String? = null,
    val updateby: String? = null,
    val City: String? = null,
    val Country: String? = null,
    val Slug: String? = null,
    val Template: String? = null,
    val Region: String? = null,
)
