package com.malka.androidappp.newPhase.domain.models.categoryFollowResp

data class FavoriteSeller(
    val branches: List<Branch>,
    val businessAccountId: String,
    val city: String,
    val createdAt: String,
    val faceBook: Any,
    val image: String,
    val isFollowed: Boolean,
    val isMerchant: Boolean,
    val lat: Any,
    val linkedIn: Any,
    val lon: Any,
    val name: String,
    val phone: String,
    val providerId: String,
    val rate: Int,
    val showUserInformation: String,
    val snapchat: Any,
    val tikTok: Any,
    val twitter: Any,
    val webSite: Any,
    val instagram: String? = null,
    val youTube: String? = null,
    val skype: String? = null,
)