package com.malka.androidappp.newPhase.domain.models.bussinessAccountsListResp

data class BusinessAccountDetials(
    val businessAccountCertificates: List<BusinessAccountCertificate>? = null,
    val businessAccountEmail: String? = null,
    val businessAccountFaceBook: String? = null,
    val businessAccountImage: String? = null,
    val businessAccountInstagram: String? = null,
    val businessAccountLinkedIn: String? = null,
    val businessAccountName: String? = null,
    val businessAccountPhoneNumber: String? = null,
    val businessAccountSnapchat: String? = null,
    val businessAccountTikTok: String? = null,
    val businessAccountTwitter: String? = null,
    val businessAccountUserName: String? = null,
    val businessAccountWebsite: String? = null,
    val businessAccountYouTube: String? = null,
    val country: String? = null,
    val createdAt: String? = null,
    val createdBy: String? = null,
    val detailRegistrationNumber: String? = null,
    val district: String? = null,
    val id: Int,
    val isActive: Boolean,
    val isDeleted: Boolean,
    val lat: String? = null,
    val lon: String? = null,
    val maroof: String? = null,
    val neighborhood: String? = null,
    val providerId: String? = null,
    val region: String? = null,
    val registrationDocumentType: String? = null,
    val registrationNumberExpiryDate: String? = null,
    val street: String? = null,
    val trade15Years: Boolean,
    val updatedBy: String? = null,
    val updatedByAt: String? = null,
    val vatNumber: String,
    val zipCode: String? = null,
    val chanegeAccountUrl: String? = null,
    var token: String? = null
)