package com.malka.androidappp.botmnav_fragments.edit_profile

data class GetUserData(
    val address: Any? = null,
    val area: Any? = null,
    val city: String? = null,
    val country: String? = null,
    val createdAt: Any? = null,
    val dateOfBirth: String? = null,
    val descriptions: Any? = null,
    val distric: String? = null,
    val email: String? = null,
    val facebook: Any? = null,
    val fullName: String? = null,
    val gender: String? = null,
    val id: String? = null,
    val idGender: Any? = null,
    val idStatus: Any? = null,
    val image: Any? = null,
    val instagram: Any? = null,
    val ipAddress: Any? = null,
    val ipArea: Any? = null,
    val ipCity: Any? = null,
    val ipCountry: Any? = null,
    val isConfirm: Boolean? = null,
    val isFavorite: Boolean? = null,
    val isForgot: Boolean? = null,
    val lastActive: Any? = null,
    val lastname: Any? = null,
    val linkedin: Any? = null,
    val notify: Boolean? = null,
    val notify_cat: Any? = null,
    val online: Boolean? = null,
    val password: String? = null,
    val phone: String? = null,
    val postCode: Any? = null,
    val refreshTokens: Any? = null,
    val region: String? = null,
    val state: Any? = null,
    val tagline: Any? = null,
    val twitter: Any? = null,
    val updatedAt: Any? = null,
    val username: String? = null,
    val views: Int? = null,
    val website: Any? = null,
    val youtube: Any? = null,
    val zipcode: String? = null
)